function  [tspan,zs]  = odde45(@(t,x) modelo_eq(t,x,u',ks,ts,reg,ns,ne,te,n_s,n_c,ne_a,ts_frozen,...
             check,tal,est,yi,optSPAIDER.prob.uref,optSPAIDER.prob.tref,optSPAIDER.prob.nref),...
             span,z0, optODE )
%UNTITLED2 Summary of this function goes here
%   Detailed explanation goes here
 [tspan,zs]  = ode45( @(t,x) modelo_eq(t,x,u',ks,ts,reg,ns,ne,te,n_s,n_c,ne_a,ts_frozen,...
             check,tal,est,yi,optSPAIDER.prob.uref,optSPAIDER.prob.tref,optSPAIDER.prob.nref),...
             span,z0, optODE )

end

